name: Ensure Tokens Registered

on:
  push:
    branches:
      - main
    paths:
      - 'tokens/registry/**'
  workflow_dispatch:

jobs:
  ensure-tokens-registered:
    strategy:
      matrix:
        network: [testnet, mainnet]

    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    env:
      NETWORK: ${{ matrix.network }}
      FLOW_ADDRESS: ${{ matrix.network == 'mainnet' && vars.MAINNET_FLOW_ADDRESS || vars.TESTNET_FLOW_ADDRESS }}
      FLOW_PRIVATE_KEY: ${{ matrix.network == 'mainnet' && secrets.MAINNET_FLOW_PRIVATE_KEY || secrets.TESTNET_FLOW_PRIVATE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd tokens
          bun install

      - name: Run token status check
        run: |
          bun run tokens/src/1-check-dirs-and-update-tokens-status.ts

      - name: Upload shortlisted contracts
        uses: actions/upload-artifact@v4
        with:
          name: shortlisted-contracts-${{ matrix.network }}
          path: tokens/outputs/${{ matrix.network }}/shortlisted-contracts.json
          if-no-files-found: error

      - name: Ensure tokens registered
        run: |
          bun run tokens/src/2-register-token-or-update-logos.ts

  update-token-list:
    runs-on: ubuntu-latest
    needs: ensure-tokens-registered

    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd tokens
          bun install
      
      - name: Download shortlisted contracts artifact - mainnet
        uses: dawidd6/action-download-artifact@v9
        with:
          workflow: ensure-tokens-registered.yml
          name: shortlisted-contracts-mainnet
          path: tokens/outputs/mainnet
          run_id: ${{ github.run_id }}

      - name: Download shortlisted contracts artifact - testnet
        uses: dawidd6/action-download-artifact@v9
        with:
          workflow: ensure-tokens-registered.yml
          name: shortlisted-contracts-testnet
          path: tokens/outputs/testnet
          run_id: ${{ github.run_id }}

      - name: Sync token list
        run: |
          bun run tokens/src/3-sync-ft-lists-with-logo-registered.ts

      # Check if any file need to be committed under tokens/outputs, if yes, go to next step, otherwise exit
      - name: Check if any file need to be committed
        id: check_changes
        run: |
          if git diff --exit-code tokens/outputs/*.*; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected in token list"
          else
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Updates were made to the token list"
          fi

      - name: Commit all updates
        if: steps.check_changes.outputs.changes == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: new tokens updated"
          branch: main
          file_pattern: "tokens/outputs/*.*"
          commit_author: "GitHub Action <actions@github.com>"
